console.log('1' == 1)
console.log('1' === 1)
console.log(3 != '3')
console.log(3 !== '3')
console.log(3 < 2)
console.log(3 > 2)
console.log(3 <= 3)
console.log(3 >= 4)

const  d1 =  new Date(0)
const  d2 =  new Date(0)
console.log('09', d1 === d2)
console.log('10', d1 == d2)
console.log('09', d1.getTime() === d2)
console.log('12', undefined == null)
console.log('13', undefined === null)